#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#
# IMPORTANT: This file's gradle-wrapper.jar counterpart is intentionally NOT
# committed as a binary in this delivery (see README "Gradle Wrapper" section).
# The CI workflow (.github/workflows/build.yml) regenerates it automatically
# with `gradle wrapper` before invoking this script, so `./gradlew build`
# works inside GitHub Actions without any manual step.
#
# If you ever run this locally and get "Could not find or load main class
# org.gradle.wrapper.GradleWrapperMain", run `gradle wrapper --gradle-version 8.9`
# once (with any locally installed Gradle) to materialize gradle/wrapper/gradle-wrapper.jar.
##############################################################################

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        exit 1
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1
    then
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
        exit 1
    fi
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
